<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ravi-PC" failures="1" tests="1" name="BrokenImagePageTest" time="16.69" errors="0" timestamp="2022-05-25T18:31:42 IST">
  <testcase classname="testcase.BrokenImagePageTest" name="verifyBrokenImages" time="4.379">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
at testcase.BrokenImagePageTest.verifyBrokenImages(BrokenImagePageTest.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyBrokenImages -->
</testsuite> <!-- BrokenImagePageTest -->
