<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ravi-PC" failures="1" tests="1" name="BrokenImagePageTest" time="10.489" errors="0" timestamp="17 May 2022 12:54:03 GMT">
  <testcase classname="testcase.BrokenImagePageTest" name="verifyBrokenImages" time="2.429">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
	at testcase.BrokenImagePageTest.verifyBrokenImages(BrokenImagePageTest.java:36)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyBrokenImages -->
</testsuite> <!-- BrokenImagePageTest -->
